### ISSUE TITLE
Renove Bot should not be trying to automerge an opened PR

### ISSUE THREAD

**Issue by oscard0m** [octokit/.github#2]
https://github.com/octokit/rest.js/pull/1988#issuecomment-765050746

Checking the presets and props of `renovate.json` is should be trying to `autoMerge`. Is this `renovate.json` the one being used or there are others extending/overriding this one?

---

If there is not one I will search for potential opened issues in Renovate Bot repo.

**Comment by JamieMagee** [comment]
This should be resolved as of this commit https://github.com/octokit/.github/commit/b3cfdba7f34e89b6a959524cbaff790a861e0f49
