### ISSUE TITLE
adjust renovate config to consider lockfile and devDependencies as chore

### ISSUE THREAD

**Issue by travi** [octokit/.github#3]
this morning, i noticed that a lockfile update was treated as a `fix` and triggered a new version to be published. i imagine this isnt what you intended, so you might want to consider taking [semanticPrefixFixDepsChoreOthers](https://docs.renovatebot.com/presets-default/#semanticprefixfixdepschoreothers) into account in [your `packageRules`](https://github.com/octokit/.github/blob/bbd05e7e30ffc9184f8d5b2e2df5e0cce5fb8dfd/renovate.json#L9-L19). 

i think just starting with 
```
    {
      "matchPackagePatterns": [
        "*"
      ],
      "semanticCommitType": "chore"
    }
```
is likely the detail that you'd want to add.

**Comment by travi** [comment]
btw, i like your rule for action updates and will probably steal that one for my own config :)

**Comment by wolfy1339** [comment]
This problem seems to be coming up again
