### ISSUE TITLE
Rename `renovate.json` to `default.json`

### ISSUE THREAD

**Issue by JamieMagee** [octokit/.github#5]
From Renovate logs

```
Fallback to renovate.json file as a preset is deprecated, please use a default.json file instead.
```

`default.json` is the new default filename for shared presets[^1]. `renovate.json` has been deprecated.

[^1]: https://docs.renovatebot.com/config-presets/

**Comment by gr2m** [comment]
we renamed it, but now we got https://github.com/octokit/.github/pull/7

**Comment by JamieMagee** [comment]
It looks like the Renovate app is installed for this repo, which caused the PR to be created. I don't think it needs to be.
