### ISSUE TITLE
Getting pull request using wrong url?

### ISSUE THREAD

**Issue by TuinboonDev** [octokit/.github#58]
### Discussed in https://github.com/orgs/octokit/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **TuinboonDev** September  9, 2023</sup>
Hello, im using this code snippet to get a single pull request:

`await context.octokit.rest.pulls.get({
      owner,
      repo,
      number
    })`
    
Except it uses this url: `https://api.github.com/repos/MYGITHUBNAME/REPO/pulls/?number=9` which gives a 404.
While I think it should be: `https://api.github.com/repos/MYGITHUBNAME/REPO/pulls/9` 

Can anyone help me out?</div>

**Comment by gr2m** [comment]
let's keep the discussion in https://github.com/orgs/octokit/discussions/57. This repository is for maintainers. Cheers.
